cameras:
  - id: camera_01
    name: "Front Eba"
    rtsp_url: "rtsp://192.168.1.11:554/ISAPI/Streaming/Channels/101"
    username: "admin"
    password: "VniiTest"
    enabled: true
    fps: 25
    resolution: "3040x1368"

  - id: camera_02
    name: "Front Hui"
    rtsp_url: "rtsp://192.168.1.12:554/ISAPI/Streaming/Channels/101"
    username: "admin"
    password: "VniiTest"
    enabled: true
    fps: 25
    resolution: "3040x1368"

  - id: camera_03
    name: "Back Pizda"
    rtsp_url: "rtsp://192.168.1.13:554/cam/realmonitor?channel=1&subtype=0"
    username: "admin"
    password: "VniiTest"
    enabled: true
    fps: 25
    resolution: "2560x1440"
    
  - id: camera_04
    name: "Back Na Kiev"
    rtsp_url: "rtsp://192.168.1.14:554/cam/realmonitor?channel=1&subtype=0"
    username: "admin"
    password: "VniiTest"
    enabled: true
    fps: 25
    resolution: "2560x1440"